### ISSUE TITLE
Crash on using assemble

### ISSUE THREAD

**Issue by Alchristis** [walksanatora/hexsky#10]
Tried to assemble a single block vector in a list and it throws an exception 
If this turns out to be some incompatibility that I was unaware of, apologies

Modlist
![image_2024-08-11_001355695](https://github.com/user-attachments/assets/991e4f0e-a113-4c30-ab31-71db6c7f35d8)

Stack
![image_2024-08-11_001707396](https://github.com/user-attachments/assets/89745068-720b-4a14-a9ea-3a4c42bd511e)

Crash log
[crash-2024-08-11_00.03.11-server.txt](https://github.com/user-attachments/files/16571533/crash-2024-08-11_00.03.11-server.txt)

**Comment by walksanatora** [comment]
oh yeah... thats probally why vs2 uses a diffrent method for single-block assemblies...
I should Probally fix that

**Comment by walksanatora** [comment]
fixed in dev
