### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Alchristis** [walksanatora/hexsky#11]
I've tried different Forge versions and VS2 versions, but my game seems to crash whenever Hexxy Skies is enabled. It generates no crash log so I've left the console log from the Prism Launcher. I did not have the same issue on the Fabric version of Hexxy Skies. 

https://pastebin.com/tpGUKt9x

Modlist
![prismlauncher_nXt01xlWsm](https://github.com/user-attachments/assets/f22ad97c-1200-4503-8b46-442b06d96f15)

**Comment by walksanatora** [comment]
found the issue
I was accidentally exporting my `EntityClipVSKt` under the wrong path

**Comment by walksanatora** [comment]
fixed in dev!
