### ISSUE TITLE
Forge: Book doesn't build, patterns don't recognize (1.0.2)

### ISSUE THREAD

**Issue by Alchristis** [walksanatora/hexsky#12]
Book doesn't build and patterns don't recognize in the forge version

This issue is not present in the fabric build

What I assume is the relevant part of log is in the pastebin

https://pastebin.com/trQTKm1r
![javaw_9vYKQau05N](https://github.com/user-attachments/assets/4a007267-3486-4b94-805d-254fb4344bfc)
![javaw_a9tvW4DCCH](https://github.com/user-attachments/assets/f6d891ab-791e-4be3-ab4a-25d2297f51e9)

If relevant, I tried this with and without Clockwork + Create installed; otherwise the only mods installed were dependencies

**Comment by walksanatora** [comment]
I uhhh swapped the order of assemble one and assemble mutiple ;-;

**Comment by walksanatora** [comment]
also I forgot to apply the pos fix to joml

**Comment by walksanatora** [comment]
fixed in dev I LOVE JOML

**Comment by awesomebossdj7** [comment]
reopen issue please, happens in 1.0.3

**Comment by walksanatora** [comment]
but also. PLEASE INCLUDE LOGS

**Comment by walksanatora** [comment]
fixed in 1.0.4
