### ISSUE TITLE
Unexpected behavior with ship assembly

### ISSUE THREAD

**Issue by Alchristis** [walksanatora/hexsky#13]
Using the assemble pattern to create a ship does not reflect in the world. 

That is to say, there is a ship type that can be referenced in the hex which it creates, but the blocks you would expect to be effected by physics are treated as typical Minecraft blocks. 
The weight pattern Tonnage Purification returns 0, and ship grabbing pattern Crow's Distillation returns null from the same block, which seems to indicate it's just not assembling. These patterns do function properly as I've tested it on a clockwork assembled ship. 

There was also an instance where assembling two blocks together caused only one to assemble successfully, but I cannot recreate it, apologies.

Also, there is still a crash when assembling a ship from a one vector list. I will post the crash log for this. 
It is still better than before when trying to assemble any ship resulted in a crash

![javaw_n2fxG77gfe](https://github.com/user-attachments/assets/10db8bae-410b-439d-aaa3-d97b3b36fc92)

[crash-2024-08-17_22.12.30-server.txt](https://github.com/user-attachments/files/16647017/crash-2024-08-17_22.12.30-server.txt)

I would upload the log file, but the log is flooded with the message
[21:15:20] [Server thread/WARN]: Ship with ID 65 has a mass of 0.0, not creating a ShipObject
Up to the point where the log is 63 MB (Varying time stamps and Ship IDs)

**Comment by walksanatora** [comment]
oh my it looks like I hard-depended on hexal  accidentally ;-;

**Comment by walksanatora** [comment]
lemme check the one-block ship
because I could have sworn it worked in dev

**Comment by walksanatora** [comment]
one block ship was using the Many assembler....
fixed in dev....
and the weight stuff should also be fixed

**Comment by walksanatora** [comment]
lemme check forge though

**Comment by walksanatora** [comment]
fixed in 1.0.5
