### ISSUE TITLE
Nature's Amusement makes ships vanish

### ISSUE THREAD

**Issue by Alchristis** [walksanatora/hexsky#14]
On assembled ships, using Nature's Amusement seems to cause the ship to vanish, whether being made larger or smaller (Tested 0.5 and 2)
The pattern which returns the scale of the ship expectedly returns 1 before the alteration, and the correct scale afterwards too. It's just gone

Tested using Clockwork assembled ships, as currently the assemble pattern seems to not work. 

Modlist
![image](https://github.com/user-attachments/assets/ddac12c7-dc96-4674-92f2-60d49263b0e1)

**Comment by TechTastic** [comment]
Fixed as of [Commit](https://github.com/walksanatora/hexsky/commit/3762706730a9e063613d7b49b30a2e1f440cbd2c)
