### ISSUE TITLE
Ship Assembly only works in positive coordinates

### ISSUE THREAD

**Issue by Alchristis** [walksanatora/hexsky#19]
Not effected by Y value

Single block and multi block assembly functions as expected in Positive X and Z coordinates

When in Negative X or Z or Both
Assembly fails and the player can no longer break blocks in the chunk where ship assembly was attempted until relogging 
(Unknown if client side relog or server restart is required)
The player is still able to break blocks in the chunk without a relog where the ship assembly was attempted IF it was a single block assembly

The log makes the same remarks as prior about making ships with 0 mass 
(It does not make these warnings for the ones properly assembled in the positive coordinates)
[latest.log](https://github.com/user-attachments/files/16684193/latest.log)

I am unable to test this in forge as it seems the patterns are still not recognized, but since the issue was already closed I will assume it is an issue with my configuration.

**Comment by walksanatora** [comment]
fixed in 1.0.5
