### ISSUE TITLE
Zone Distillations do not function with HexSky installed

### ISSUE THREAD

**Issue by Alchristis** [walksanatora/hexsky#20]
Try to properly execute a zone distillation with HexSky installed, and it causes this error. This pattern works with VS2 and Create: Clockwork installed - adding HexSky causes the error. 

![image](https://github.com/user-attachments/assets/a718a889-f276-4aa0-ad88-6e9dfae0d3b2)
[latest.log](https://github.com/user-attachments/files/16733760/latest.log)

**Comment by walksanatora** [comment]
it broke AGAIN ugg.

**Comment by walksanatora** [comment]
can you check this again on 1.0.4

**Comment by walksanatora** [comment]
fixed in 1.0.5
